spring:
  profiles:
    group:
      default: "default"
      real : "real,real-db"
  config:
    import: classpath:application-data.yml
---
spring:
  config:
    activate:
      on-profile: default
server:
  port: 80
---
spring:
  config:
    activate:
      on-profile: real
server:
  port: 8080